name: diffsbdd
channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip=24.2
  - pytorch=2.0.1=*cuda11.8*
  - cudatoolkit=11.8
  - pytorch-lightning=1.8.4
  - wandb=0.13.1
  - rdkit=2022.03.2
  - biopython=1.79
  - imageio=2.21.2
  - scipy=1.13.1
  - pytorch-scatter=2.1.2
  - networkx=3.3
  - numpy=1.26.4
  - openbabel=3.1.1
  - pandas=2.2.2  
  - seaborn=0.13.2
  - torchmetrics=1.4.2
  - tqdm=4.66.5
  - yaml=0.2.5
  - protobuf=3.20.*
